services:
  devnet:
    image: shardlabs/starknet-devnet:next
    ports:
    - 5050:5050

  apibara-starknet:
    image: apibara/starknet:1984713d4002334823c37bc8131ee8e55e2bcf3b
    command:
    - apibara-starknet
    - start
    - --rpc=http://devnet:5050/rpc
    ports:
    - 7171:7171
    restart: always
    depends_on:
      - devnet
